version: "3"
services:
  ui:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports: 
      - "3000:3000"
    depends_on: 
      - db
  db:
    image: couchdb:2
    ports: 
      - "5984:5984"
    volumes:
      - "./db_data:/opt/couchdb/data"
