version: "3"
services:
  ui:
    image: node:8-alpine
    volumes:
      - "./:/app/"
    working_dir: "/app"
    command: "npm start"
    ports: 
      - "3000:3000"
  db:
    image: couchdb:2
    ports: 
      - "5984:5984"
    volumes:
      - "./db_data:/opt/couchdb/data"